"""rename_apply_id_to_vacancy_id_and_state_type_to_stage_type

Revision ID: 5b3538f6be69
Revises: 82ccf024c34c
Create Date: 2025-07-20 00:56:44.454753

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b3538f6be69"
down_revision: Union[str, None] = "82ccf024c34c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем новые колонки как nullable
    op.add_column("stage", sa.Column("vacancy_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "stage", sa.Column("stage_type", sa.String(length=255), nullable=True)
    )

    # Копируем данные из старых колонок в новые
    op.execute("UPDATE stage SET vacancy_id = apply_id, stage_type = state_type")

    # Делаем новые колонки NOT NULL
    op.alter_column("stage", "vacancy_id", nullable=False)

    # Удаляем старые foreign key и колонки
    op.drop_constraint("stage_apply_id_fkey", "stage", type_="foreignkey")
    op.create_foreign_key(
        None, "stage", "vacancy", ["vacancy_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("stage", "state_type")
    op.drop_column("stage", "apply_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stage", sa.Column("apply_id", sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "stage",
        sa.Column(
            "state_type", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "stage", type_="foreignkey")
    op.create_foreign_key(
        "stage_apply_id_fkey",
        "stage",
        "vacancy",
        ["apply_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("stage", "stage_type")
    op.drop_column("stage", "vacancy_id")
    # ### end Alembic commands ###
