"""updateded_stage_model

Revision ID: 1321c553570f
Revises: 6e3172213a46
Create Date: 2025-08-03 20:33:36.103150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1321c553570f'
down_revision: Union[str, None] = '6e3172213a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('title', sa.Text(), nullable=True))
    op.drop_column('stage', 'occurred_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('occurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('stage', 'title')
    # ### end Alembic commands ###
