services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - applyr_network

  api:
    build: ${LOCAL_MODE:-./api}
    image: applyr.cr.cloud.ru/applyr-api:latest
    ports:
      - "80:8000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ${LOCAL_MODE:-./api:/app}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - applyr_network

  bot:
    build: ${LOCAL_MODE:-./bot}
    image: applyr.cr.cloud.ru/applyr-bot:latest
    environment:
      API_URL: ${API_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - api
    networks:
      - applyr_network

volumes:
  postgres_data:

networks:
  applyr_network:
    driver: bridge 