"""fixed favorite model

Revision ID: 73212e50701a
Revises: 264a44ef68ab
Create Date: 2025-09-21 12:44:47.129476

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '73212e50701a'
down_revision: str | None = '264a44ef68ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('favorite', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('favorite', 'notes')
    # ### end Alembic commands ###
