"""database recreation

Revision ID: 6bdb5b224bab
Revises:
Create Date: 2025-09-15 20:21:57.256671

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6bdb5b224bab"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE roles AS ENUM ('user', 'admin')")
    op.add_column("user", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "user", sa.Column("first_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "user", sa.Column("second_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "user",
        sa.Column(
            "role", postgresql.ENUM("USER", "ADMIN", name="roles"), nullable=True
        ),
    )
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "role")
    op.drop_column("user", "second_name")
    op.drop_column("user", "first_name")
    op.drop_column("user", "email")
    op.execute("DROP TYPE roles")
    # ### end Alembic commands ###
