"""updated user

Revision ID: 5d1d20c1e9a7
Revises: 8bc1f6aef7f7
Create Date: 2025-09-15 20:56:06.914913

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "5d1d20c1e9a7"
down_revision: str | None = "8bc1f6aef7f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
