"""updated user

Revision ID: f348c0466b8e
Revises: 6bdb5b224bab
Create Date: 2025-09-15 20:33:02.336860

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f348c0466b8e"
down_revision: str | None = "6bdb5b224bab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
