"""fixed favorite model

Revision ID: cd1d62dae9ec
Revises: 73212e50701a
Create Date: 2025-09-21 13:29:23.245378

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd1d62dae9ec"
down_revision: str | None = "73212e50701a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("favorite", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(
        None, "favorite", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "favorite", type_="foreignkey")
    op.drop_column("favorite", "user_id")
    # ### end Alembic commands ###
