"""database create

Revision ID: 60ac7a31afbf
Revises:
Create Date: 2025-09-15 17:01:01.407995

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "60ac7a31afbf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
