"""updated user

Revision ID: 8bc1f6aef7f7
Revises: f348c0466b8e
Create Date: 2025-09-15 20:48:10.271387

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "8bc1f6aef7f7"
down_revision: str | None = "f348c0466b8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
