"""added stage to favorite model

Revision ID: ce370760a9d5
Revises: cd1d62dae9ec
Create Date: 2025-09-21 22:04:33.887757

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce370760a9d5"
down_revision: str | None = "cd1d62dae9ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    favorite_stage = postgresql.ENUM(
        "NOTHING",
        "APPLY_SENT",
        "HR_INTERVIEW",
        "TECH_INTERVIEW",
        "BUSINESS_INTERVIEW",
        "WAITING_FEEDBACK",
        "REJECTED",
        "OFFER_RECEIVED",
        "ARCHIVE",
        name="favorite_stage",
    )
    favorite_stage.create(op.get_bind())
    op.add_column("favorite", sa.Column("stage", favorite_stage, nullable=True))
    op.execute("UPDATE favorite SET stage = 'NOTHING' WHERE stage IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorite", "stage")
    op.execute("DROP TYPE favorite_stage")
    # ### end Alembic commands ###
