"""updated user

Revision ID: f6c16d37f2ad
Revises: 5d1d20c1e9a7
Create Date: 2025-09-15 21:07:15.116618

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6c16d37f2ad"
down_revision: str | None = "5d1d20c1e9a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    op.add_column(
        "user",
        sa.Column(
            "role", postgresql.ENUM("user", "admin", name="roles"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    op.add_column(
        "user",
        sa.Column(
            "role", postgresql.ENUM("USER", "ADMIN", name="roles"), nullable=True
        ),
    )
    # ### end Alembic commands ###
