"""updated vacancy

Revision ID: 1575244dada5
Revises: c709412ff4c1
Create Date: 2025-09-21 12:24:47.643321

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1575244dada5"
down_revision: str | None = "c709412ff4c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vacancy_status = postgresql.ENUM(
        "DRAFT", "MODERATION", "PUBLISHED", "EXPIRED", name="vacancy_status"
    )
    vacancy_status.create(op.get_bind())
    op.add_column("vacancy", sa.Column("status", vacancy_status, nullable=True))
    op.add_column("vacancy", sa.Column("contact_link", sa.Text(), nullable=True))
    op.execute("UPDATE vacancy SET status = 'DRAFT' WHERE status IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancy", "contact_link")
    op.drop_column("vacancy", "status")
    op.execute("DROP TYPE vacancy_status")
    # ### end Alembic commands ###
